apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
  labels:
     app: java-maven-app
spec:
  replicas: 20
  selector:
    matchLabels:
      app: java-maven-app
  template:
    metadata:
      labels:
        app: java-maven-app
    spec:
      imagePullSecrets:
      - name: docker-key
      containers:
      - name: sample-ctr
        image: $IMAGE_NAME:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
      app: java-maven-app
spec:
  selector:
    app: java-maven-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer